/**
 * Every query parameter `/blog` accepts, normalised before anything touches the
 * database.
 *
 * Two unauthenticated 500s came from the absence of this file. `q` went
 * straight into a raw SQL parameter, so a NUL byte reached Postgres and came
 * back as `22021 invalid byte sequence for encoding "UTF8"`. `page` went
 * straight into Prisma's `skip`, so `?page=1e999` became `skip: Infinity` and
 * `?page=999999999999999999999` became `skip: 9e+21`, neither of which is an
 * Int. Both were one GET, no auth, on the site's main content route — and
 * repeated 5xx there is what suppresses crawl rate for a whole domain.
 *
 * The rule this file enforces: a request either names a page that could exist,
 * or it is answered with a redirect or a 404. It is never allowed to become a
 * database error.
 */

/**
 * The highest page number worth asking the database about.
 *
 * At nine posts per page this is 4,500 articles, which is far beyond anything
 * this blog will hold. The point is to have a bound at all: without one, a
 * crawler following a mistyped link generates an unbounded set of URLs that
 * each cost a COUNT and a paginated SELECT before returning nothing.
 */
export const MAX_PAGE = 500;

/** Long enough for a real search, short enough that the ILIKE stays cheap. */
export const MAX_QUERY_LENGTH = 80;

/** Slugs are generated by `slugify`, so anything longer is not one of ours. */
const MAX_SLUG_LENGTH = 120;

export type RawBlogParams = {
  page?: string | string[];
  q?: string | string[];
  kategori?: string | string[];
};

export type BlogParams = {
  page: number;
  /** Sanitised. Empty means "not a search". */
  query: string;
  /** Empty means "no category filter". */
  categorySlug: string;
  /**
   * The URL this request should have used.
   *
   * When it differs from the request's own path, the page redirects there —
   * which is how `?page=abc`, `?page=0` and `?page=1` stop existing as
   * separate, indexable URLs saying the same thing as `/blog`.
   */
  canonicalPath: string;
  /**
   * True when the page number is syntactically fine but beyond `MAX_PAGE`.
   * The caller answers 404 without querying anything.
   */
  beyondLimit: boolean;
};

/**
 * Next gives a repeated parameter as an array. Taking the first is the same
 * choice `URLSearchParams.get` makes, and it means `?page=1&page=abc` cannot
 * behave differently from `?page=1`.
 */
const first = (value: string | string[] | undefined) =>
  Array.isArray(value) ? value[0] : value;

/**
 * Strips what has no business in a search box.
 *
 * The C0 range includes the NUL byte that produced the 500 — Postgres text
 * cannot hold one at any encoding — and every other control character is
 * equally meaningless here. Whitespace is collapsed so `"a     b"` and `"a b"`
 * are one search rather than two cache entries.
 */
function sanitiseQuery(raw: string | undefined) {
  if (!raw) return "";

  // Compared by code point rather than matched by a regex: a character class
  // spanning the C0 range has to be written with literal control bytes or with
  // escapes, and both are things a formatter or a careless save can quietly
  // mangle. This cannot be mangled.
  let cleaned = "";
  for (const character of raw) {
    const code = character.codePointAt(0) ?? 0;
    cleaned += code < 0x20 || code === 0x7f ? " " : character;
  }

  return cleaned.replace(/\s+/g, " ").trim().slice(0, MAX_QUERY_LENGTH);
}

function sanitiseSlug(raw: string | undefined) {
  if (!raw) return "";

  const trimmed = raw.trim().slice(0, MAX_SLUG_LENGTH);
  // Anything outside the shape `slugify` produces cannot match a stored slug,
  // so it is dropped here rather than sent to the database to find that out.
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(trimmed) ? trimmed : "";
}

/**
 * A page number, or null when the input is not one.
 *
 * `Number()` is deliberately not trusted on its own: it maps `""` and `" "` to
 * 0, `"1e999"` to Infinity and `"2.5"` to a non-integer, and every one of those
 * used to flow into `skip`. Requiring a plain run of digits first means only
 * integers ever reach the arithmetic.
 */
function parsePage(raw: string | undefined) {
  if (raw === undefined) return 1;
  if (!/^\d+$/.test(raw.trim())) return null;

  const parsed = Number(raw.trim());
  return Number.isSafeInteger(parsed) && parsed >= 1 ? parsed : null;
}

export function buildBlogPath(page: number, categorySlug: string, query: string) {
  const search = new URLSearchParams();
  if (query) search.set("q", query);
  if (categorySlug) search.set("kategori", categorySlug);
  // Page 1 is `/blog`, never `/blog?page=1` — one page, one URL.
  if (page > 1) search.set("page", String(page));

  const qs = search.toString();
  return qs ? `/blog?${qs}` : "/blog";
}

export function parseBlogParams(raw: RawBlogParams): BlogParams {
  const query = sanitiseQuery(first(raw.q));
  const categorySlug = sanitiseSlug(first(raw.kategori));
  const parsed = parsePage(first(raw.page));

  /**
   * Unparseable page numbers collapse to page 1 rather than 404.
   *
   * `?page=abc` is a typo or a broken link, and the useful answer is the first
   * page of the archive. `canonicalPath` then differs from the request, so the
   * caller redirects and the malformed URL does not survive as its own entry in
   * anyone's index.
   */
  const page = parsed ?? 1;
  const beyondLimit = page > MAX_PAGE;

  return {
    page,
    query,
    categorySlug,
    canonicalPath: buildBlogPath(page, categorySlug, query),
    beyondLimit,
  };
}

/**
 * The path this request arrived on, in the same normalised form
 * `canonicalPath` produces — so the two can be compared to decide on a
 * redirect.
 */
export function requestedBlogPath(raw: RawBlogParams) {
  const search = new URLSearchParams();
  const q = first(raw.q);
  const kategori = first(raw.kategori);
  const page = first(raw.page);

  if (q !== undefined) search.set("q", q);
  if (kategori !== undefined) search.set("kategori", kategori);
  if (page !== undefined) search.set("page", page);

  const qs = search.toString();
  return qs ? `/blog?${qs}` : "/blog";
}
